"""add_rating_column_to_posts

Revision ID: d341dbb172d0
Revises: d6dfe698ac83
Create Date: 2026-04-20 22:01:11.751726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd341dbb172d0'
down_revision: Union[str, Sequence[str], None] = 'd6dfe698ac83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'rating')
    # ### end Alembic commands ###
